[build]
  publish = "public"
  command = "make build"
  functions = "functions"

[build.environment]
  # change this to your repository path
  GO_IMPORT_PATH = "https://github.com/bloodiator2/telegram-form-notification-bot"
